version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - |
        cat <<EOT >> "./.env"
        REPORT_ADVANCED_API_ENDPOINT="$REPORT_ADVANCED_API_ENDPOINT"
        REPORT_API_ENDPOINT="$REPORT_API_ENDPOINT"
        REPORT_API_KEY="$REPORT_API_KEY"
        NEXT_PUBLIC_HOSTING_PATH="$NEXT_PUBLIC_HOSTING_PATH"
        EMAIL_HOST="$EMAIL_HOST"
        EMAIL_USER="$EMAIL_USER"
        EMAIL_PASS="$EMAIL_PASS"
        USE_LOCAL_CMS_DATA="$USE_LOCAL_CMS_DATA"
        CMS_API_ENDPOINT="$CMS_API_ENDPOINT"
        ENQUIRY_RECIPIENT_EMAIL="$ENQUIRY_RECIPIENT_EMAIL"
        JOIN_US_RECIPIENT_EMAIL="$JOIN_US_RECIPIENT_EMAIL"
        NEXT_PUBLIC_SITE_URL="$NEXT_PUBLIC_SITE_URL"
        NEXT_PUBLIC_GOOGLE_ANALYTICS="$NEXT_PUBLIC_GOOGLE_ANALYTICS"
        EOT
      - yarn
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  enable-symlinks: yes
