version: '3.9'

services:
    frontend:
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - .env.local
        ports:
            - 8080:8080
        volumes:
            - ./:/app
            - /app/node_modules